### PR TITLE
Fix android native locator support for appium helper

### LINKED ISSUE #2428: [Bug] Appium helper does not work with android native locator
#### What are you trying to achieve?
Use android native locator for the element

#### What do you get instead?

> Provide console output if related. Use `--verbose` mode for more details.

```bash
element (android=new UiSelector().text("android=new UiSelector().resourceId('com.xxx/imageView')")) still not visible after 90 sec
```

> Provide test source code if related

```js
const imgBanner = "android=new UiSelector().resourceId('com.xxx:id/imageView')"
I.seeElement(imgBanner);
```

### Details
* CodeceptJS version: 2.6.5
* NodeJS Version: Any
* Operating System: Any
* Appium helper

### PR DESCRIPTION
**Pull request by idxn**
## Motivation/Description of the PR
- Currently, appium helper does not work with android native locator so this pr is made to resolve #2428 
- Update doc for android typo
- Update FileHelper unit test to work correctly on windows platform

Applicable helpers:
- [X] Appium

## Type of change

- [x] :rocket: New functionality
- [x] :bug: Bug fix
- [x] :clipboard: Documentation changes/updates

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [ ] Local tests are passed (Run `npm test`)

### CODE REVIEW

**Comment by idxn** [comment]
@PeterNgTr @DavertMik Could you please review and approve? Many thanks, guys!

**Comment by idxn** [comment]
i'm not sure why the appium test is not executed.

**Comment by PeterNgTr** [comment]
Cool. Looks like this PR fixes current issues on appium helper like scroll, tap, etc. regarding the tests, I don’t know. Maybe @davert is fixing something there.

**Comment by idxn** [comment]
@DavertMik without code changes, the native locator won't work.

**Comment by idxn** [comment]
> Thank you, that was bad a problem replace :)
> But could you update PR to include only doc changes, and not code changes

I don't get what you are saying. The native locator won't work without code changes.

**Comment by DavertMik** [comment]
@idxn sorry, I didn't explain things a right way. Just woke up so sorry about this.

Here is what I meant:

* doc changes = ok
* code changes = it is hard to review them as most of diffs I see is formatting changes. Could you streamline your PR only to actual code changes, and not includ formatting updates

**Comment by idxn** [comment]
@DavertMik linter fix is reverted. please kindly review and provide any feedbacks

**Comment by DavertMik** [comment]
Thanks, looks good to me!

**Pull request merged**
