### PR TITLE
refactor: Transform Recorder into class with static methods

### PR DESCRIPTION
**Pull request by elukoyanov**
## Motivation/Description of the PR

Applicable helpers:

- [ ] Webdriver
- [ ] Puppeteer
- [ ] Nightmare
- [ ] REST
- [ ] Appium
- [ ] Protractor
- [ ] TestCafe

- Description of this PR, which problem it solves
- A link to the corresponding issue (if applicable).

Make `recorder` a static class instead of module object:
1. `recorder` and it's internal `RecorderSession` include `catch` method. It's not allowed to create non-class methods with reserved word names.
2. Problem described upper creates problem with typings. Typescript deny use of reserved words by default. And it leads to incompatible with most of users TS settings.
3. definition_test fails 
3. `recorder` is kind of entity. And entities should be created as class

## Type of change

- [ ] Breaking changes
- [ ] New functionality
- [x] Bug fix
- [ ] Documentation changes/updates
- [ ] Hot fix
- [ ] Markdown files fix - not related to source code

## Checklist:

- [ ] Tests have been added
- [ ] Documentation has been added (Run `npm run docs`)
- [x] Lint checking (Run `npm run lint`)
- [x] Local tests are passed (Run `npm test`)

## Notes
Linter fails on static fields definition: `static sessions = [];`.
Cause old eslint (compatible with ES5, not with ES6) does not support it.
#2112 should be merged first. Or this PR should be to that branch.
Therefore, it's Draft PR until eslint is updated.

Moreover, edit will be need until eslint update.

### CODE REVIEW

**Comment by DavertMik** [comment]
Great! Personally, I like the current recorder but I'm not going to oppose progress. :+1:

**Comment by DavertMik** [comment]
@elukoyanov any updates?

**Comment by DavertMik** [comment]
@elukoyanov this PR is still a draft. We have a few more days before releasing CodeceptJS 3
If you want to get it merged please update it, so we could include it into release

**Comment by elukoyanov** [comment]
Static class does not much differs from simple module, so i'll close PR.

Maybe it's better to use singleton object created from class. Maybe no

**Pull request closed without merging**
